package view;

import model.User;
import service.AppService;
import utils.AppTheme;
import view.components.RoundedButton;
import view.components.RoundedPanel;
import view.components.UiFactory;
import javax.swing.*;
import java.awt.*;

public class LoginFrame extends JFrame {
    private final AppService service;private final JTextField username=UiFactory.field();private final JPasswordField password=new JPasswordField();
    public LoginFrame(AppService service){super("Đăng nhập - Sales Management");this.service=service;setDefaultCloseOperation(EXIT_ON_CLOSE);setResizable(false);setSize(860,540);setLocationRelativeTo(null);JPanel root=new JPanel(new GridLayout(1,2));JPanel hero=new JPanel(new GridBagLayout());hero.setBackground(AppTheme.SIDEBAR);JPanel heroText=new JPanel();heroText.setOpaque(false);heroText.setLayout(new BoxLayout(heroText,BoxLayout.Y_AXIS));JLabel logo=new JLabel("SALES PRO");logo.setForeground(Color.WHITE);logo.setFont(AppTheme.FONT.deriveFont(Font.BOLD,34));JLabel sub=new JLabel("Quản lý bán hàng đơn giản và hiệu quả");sub.setForeground(new Color(0xCBD5E1));sub.setFont(AppTheme.FONT.deriveFont(15f));heroText.add(logo);heroText.add(Box.createVerticalStrut(10));heroText.add(sub);hero.add(heroText);root.add(hero);JPanel area=new JPanel(new GridBagLayout());area.setBackground(AppTheme.BACKGROUND);RoundedPanel form=new RoundedPanel(Color.WHITE);form.setPreferredSize(new Dimension(330,370));form.setLayout(new BoxLayout(form,BoxLayout.Y_AXIS));form.setBorder(BorderFactory.createEmptyBorder(36,34,30,34));JLabel title=new JLabel("Chào mừng trở lại");title.setFont(AppTheme.FONT.deriveFont(Font.BOLD,24));title.setForeground(AppTheme.TEXT);title.setAlignmentX(LEFT_ALIGNMENT);form.add(title);JLabel hint=new JLabel("Đăng nhập để tiếp tục");hint.setForeground(AppTheme.MUTED);hint.setAlignmentX(LEFT_ALIGNMENT);form.add(hint);form.add(Box.createVerticalStrut(25));form.add(label("Tên đăng nhập"));username.setMaximumSize(new Dimension(Integer.MAX_VALUE,40));username.setAlignmentX(LEFT_ALIGNMENT);form.add(username);form.add(Box.createVerticalStrut(14));form.add(label("Mật khẩu"));password.setFont(AppTheme.FONT);password.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(AppTheme.BORDER),BorderFactory.createEmptyBorder(6,10,6,10)));password.setMaximumSize(new Dimension(Integer.MAX_VALUE,40));password.setAlignmentX(LEFT_ALIGNMENT);form.add(password);JCheckBox show=new JCheckBox("Hiện mật khẩu");show.setOpaque(false);show.setFont(AppTheme.FONT);show.setAlignmentX(LEFT_ALIGNMENT);char echo=password.getEchoChar();show.addActionListener(e->password.setEchoChar(show.isSelected()?(char)0:echo));form.add(Box.createVerticalStrut(6));form.add(show);form.add(Box.createVerticalStrut(14));RoundedButton login=new RoundedButton("ĐĂNG NHẬP",AppTheme.PRIMARY);login.setMaximumSize(new Dimension(Integer.MAX_VALUE,44));login.setAlignmentX(LEFT_ALIGNMENT);login.addActionListener(e->login());form.add(login);area.add(form);root.add(area);setContentPane(root);getRootPane().setDefaultButton(login);username.setText("admin");password.setText("123456");}
    private JLabel label(String text){JLabel l=new JLabel(text);l.setForeground(AppTheme.TEXT);l.setFont(AppTheme.FONT.deriveFont(Font.BOLD));l.setAlignmentX(LEFT_ALIGNMENT);return l;}
    private void login(){String u=username.getText().trim(),p=new String(password.getPassword());User user=service.login(u,p).orElse(null);if(user==null){JOptionPane.showMessageDialog(this,"Tên đăng nhập hoặc mật khẩu không chính xác.","Đăng nhập thất bại",JOptionPane.ERROR_MESSAGE);password.selectAll();password.requestFocus();return;}dispose();new MainFrame(service,user).setVisible(true);}
}
